A home renting startup, Ghar ki Baat, is planning to offer 2 BHK fully furnished flats for rent in Powai, Mumbai. In order to ensure that it charges the correct rent, it wants to find the average rent charged by homeowners in Powai.

 

For that purpose, it has acquired the following data, which has a list of 200 fully furnished 2 BHK flats in Powai, along with the monthly rent charged for them in the year 2016.

As a data analyst working for Ghar ki Baat, you are tasked with finding the average rent for all 2 BHK fully furnished flats in Powai, Mumbai, using this data.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('Inferential Statistics - Powai Flats Rent.csv')

In [3]:
df.head()

S. No.  Monthly Rent
0       1         44000
1       2         49800
2       3         45400
3       4         40700
4       5         43900

In [4]:
df.describe()

S. No.  Monthly Rent
count  200.000000    200.000000
mean   100.500000  45571.000000
std     57.879185   7457.521851
min      1.000000  30100.000000
25%     50.750000  41250.000000
50%    100.500000  44950.000000
75%    150.250000  49825.000000
max    200.000000  59800.000000

In [5]:
print(np.std(df['Monthly Rent'], ddof=1))

7457.521851178448


In [6]:
print(np.std(df))

S. No.            57.734305
Monthly Rent    7438.854683
dtype: float64


#### 1. What is the 90% confidence interval for the monthly rent in rupees?

In [7]:
44701,46441

(44701, 46441)

Coding Questions(Graded) Centeral Limit Theoram

Description
Generate a binomial distribution, tested 10 times, given the number of trials(n) and probability(p) of each trial.
The input will contain seed, n and p in the same order.
The output should contain a numpy array with 10 numbers representing the required binomial distribution.
Hint: You can use numpy's random number generator here too. Remember to set the seed before generating numbers to ensure correct output.
Sample Input:
0
10
0.5
Sample Output:
[5 6 5 5 5 6 5 7 8 5]

### Program

Inderectly here we are trying to Caluculate nCr*p^r*(1-p)^(n-r))

N=Number of total items
r= possible subsets

In [8]:
def nCr(n,r):
    if (r > n / 2): 
        r = n - r; 
  
    answer = 1; 
    for i in range(1, r + 1): 
        answer *= (n - r + i); 
        answer /= i; 
  
    return answer; 

In [9]:
nCr(4,2)

6.0

In [10]:
def binomialProbability(n, k, p): 
  
    return (nCr(n, k) * pow(p, k) * 
                        pow(1 - p, n - k));

In [11]:
n = 10; 
k = 5; 
p = 1.0 / 3; 
  
probability = binomialProbability(n, k, p);

print("Probability of", k,  
      "heads when a coin is tossed", end = " "); 
print(n, "times where probability of each head is",  
                                      round(p, 6)); 
print("is = ", round(probability, 6)); 

Probability of 5 heads when a coin is tossed 10 times where probability of each head is 0.333333
is =  0.136565


In [12]:
import random 

In [13]:
for i in range(5):
    # Any number can be used in place of 0.
    random.seed(0)
    # Generated random number will be between 1 to 1000.
    randomNo = random.randint(1, 10)
    n = randomNo; 
    0
    k=10
    p=0.5 

    probability = binomialProbability(n, k, p);
    print(probability); 

0.0078125
0.0078125
0.0078125
0.0078125
0.0078125


In [14]:
n=10
p=0.5

np.random.seed(0)
s = np.random.binomial(n, p, 10)
print(s)

[5 6 5 5 5 6 5 7 8 5]


In [15]:
from scipy.stats import zscore

In [16]:
help(zscore)

Help on function zscore in module scipy.stats.stats:

zscore(a, axis=0, ddof=0, nan_policy='propagate')
    Compute the z score.
    
    Compute the z score of each value in the sample, relative to the
    sample mean and standard deviation.
    
    Parameters
    ----------
    a : array_like
        An array like object containing the sample data.
    axis : int or None, optional
        Axis along which to operate. Default is 0. If None, compute over
        the whole array `a`.
    ddof : int, optional
        Degrees of freedom correction in the calculation of the
        standard deviation. Default is 0.
    nan_policy : {'propagate', 'raise', 'omit'}, optional
        Defines how to handle when input contains nan. 'propagate' returns nan,
        'raise' throws an error, 'omit' performs the calculations ignoring nan
        values. Default is 'propagate'.
    
    Returns
    -------
    zscore : array_like
        The z-scores, standardized by mean and standard deviation of
 

In [21]:
zscore([[70, 80, 90, 100, 110,120,130]] ,axis=1)

array([[-1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5]])

In [56]:
print((100-90)/10)

1.0


In [28]:
zscore([[90,100]],axis=1)

array([[-1.,  1.]])

In [29]:
zscore([[100,90]],axis=1)

array([[ 1., -1.]])

In [104]:
m=100
sd=10
z = float((m-90)/sd) 
a=[] 
a.append(z)
print(a)
print(zscore(a,axis=0))

[1.0]
[nan]


In [106]:
round(3.60,2)

3.6

In [107]:
round(3.6,2)

3.6

In [111]:
x=(15-3)/(15-1)

In [113]:
round(x,4)

0.8571

In [33]:
data = np.array([6, 7, 7, 12, 13, 13, 15, 16, 19, 22])

In [36]:
np.mean(data)

13.0

In [37]:
np.median(data)

13.0

In [39]:
zscore(data,axis=0)

array([-1.39443338, -1.19522861, -1.19522861, -0.19920477,  0.        ,
        0.        ,  0.39840954,  0.5976143 ,  1.19522861,  1.79284291])

In [45]:
mean=100
sd=10
data=pd.DataFrame([mean-3*sd,mean-2*sd,mean-1*sd,mean,mean+1*sd,mean+2*sd,mean+3*sd], columns=['A'])

In [47]:
data.head(10)

A
0   70
1   80
2   90
3  100
4  110
5  120
6  130

In [50]:
import scipy.stats as stats

In [51]:
data.apply(stats.zscore)

A
0 -1.5
1 -1.0
2 -0.5
3  0.0
4  0.5
5  1.0
6  1.5

In [53]:
m=100
sd=10
# P(X<90)
z = float((m-90)/sd) 
a=[] 
a.append(z)
print(a)

[1.0]


In [54]:
from math import *
def erfcc(x):
    """Complementary error function."""
    z = abs(x)
    t = 1. / (1. + 0.5*z)
    r = t * exp(-z*z-1.26551223+t*(1.00002368+t*(.37409196+
        t*(.09678418+t*(-.18628806+t*(.27886807+
        t*(-1.13520398+t*(1.48851587+t*(-.82215223+
        t*.17087277)))))))))
    if (x >= 0.):
        return r
    else:
        return 2. - r

def ncdf(x):
    return 1. - 0.5*erfcc(x/(2**0.5))

In [56]:
round(ncdf(1.0),2)

0.84

In [61]:
m=100
sd=10
from math import *
def erfcc(x):
    """Complementary error function."""
    z = abs(x)
    t = 1. / (1. + 0.5*z)
    r = t * exp(-z*z-1.26551223+t*(1.00002368+t*(.37409196+
        t*(.09678418+t*(-.18628806+t*(.27886807+
        t*(-1.13520398+t*(1.48851587+t*(-.82215223+
        t*.17087277)))))))))
    if (x >= 0.):
        return r
    else:
        return 2. - r

def ncdf(x):
    return 1. - 0.5*erfcc(x/(2**0.5))
    
z=float((m-90)/sd)
print(round(ncdf(z),2))

0.84


In [63]:
from scipy.stats import norm
round(norm.cdf(z),2)

0.84