## Valid email ID
Description
Consider that email IDs are supposed to be for the following format:

username@website.extension.

Here, there are three conditions to keep in mind:
1. The username can only contain characters 0-9, a-z and A-Z.
2. The website name can contain only characters a-z
3. The extension can have 2 or 3 alphabets(a-z).

Given an email ID, you have to determine if it is valid or not.

Sample Input:

prerna@upgrad.com

Sample Output:

valid

In [16]:
import re

In [17]:
regex='^[a-z0-9A-Z]+[@][a-z]+[.]\w{2,3}$'
def checkmail(email):
    # pass the regular expression 
    # and the string in search() method 
    if(re.search(regex,email)):  
        return "valid" 
    else:  
         return "invalid"
        

##contains . not valid
email='pre.na@upgrad.com'
print(checkmail(email))
## contains _ not valid
email='pre_na@upgrad.com'
print(checkmail(email))

##contains caps P in uPgrad false second conditions. so invalid
email='pre_na@uPgrad.com'
print(checkmail(email))

## only two or three chracter allowed otherwise false
email='prerna@upgrad.comm'
print(checkmail(email))
email='prerna@upgrad.c'
print(checkmail(email))

##The username can only contain characters 0-9, a-z and A-Z.
## Only contains 0-9,a-z and A-Z, so valid
email='preRna9@upgrad.com'
print(checkmail(email))

invalid
invalid
invalid
invalid
invalid
valid


## Flatten a list
Description
Given a nested list, write python code to flatten the list.

Note: The input list will strictly have 2 levels, i.e. the list will be of the form [[1,2],[3,4]]. Inputs like [1,[2,3]] and [[1,[2,3],4],5] are not applicable.

For example: If the input list is :
[[1,2,3],[4,5],[6,7,8,9]]

Then the output should be:
[1,2,3,4,5,6,7,8,9]

In [18]:
flatten_list=lambda t: [item for sublist in t for item in sublist]

In [19]:
print(flatten_list([[1,2,3],[4,5],[6,7,8,9]] ))

[1, 2, 3, 4, 5, 6, 7, 8, 9]


## Squares
### Description
Given a list of positive integers, you have to find numbers divisible by 3 and replace them with their squares. 

For example, consider the list below:

Input: [1,2,3,4,5,6]

The output for the above list would be: [1,2,9,4,5,36]. Because 3 and 6 were divisible by 3, these numbers were replaced with their squares.

In [20]:
numbers = [1, 2, 3, 4, 5,6]

squared_numbers = [number ** 2 if number%3==0 else number for number in numbers]

print(squared_numbers)

[1, 2, 9, 4, 5, 36]


## A weird sum
### Description
Write a program that computes the value of n+nn+nnn+nnnn with a given digit as the value of n.

For example, if n=9 , then you have to find the value of 9+99+999+9999.

In [21]:
def findResult(n):
    x=str(n)
    return int(x*1)+int(x*2)+int(x*3)+int(x*4)
findResult(9)

11106

## 2D array
### Description
Write Python code which takes 2 numbers x and y as input and generates a 2-dimensional numpy array where value in
the i-th row and j-th column of the array should be (i+j)/2.<br>
Note: i=0,1,...x-1 and j=0,1....,y-1<br>
The input will have two lines with x and y respectively.<br>
The output should be a 2D numpy array.<br>
Sample Input:<br>
3<br>
4<br>
Sample Output:<br>
[[0.  0.5 1.  1.5]<br>
 [0.5 1.  1.5 2. ]<br>
 [1.  1.5 2.  2.5]]<br>

In [22]:
import numpy as np
def listNested(x,y):
    array = [[(i+j)/2 for j in range(y)] for i in range(x)]
    ar = np.matrix(array)
    return ar
print(listNested(3,4))

[[0.  0.5 1.  1.5]
 [0.5 1.  1.5 2. ]
 [1.  1.5 2.  2.5]]


In [23]:
x = []
for d in range(0,66):
    x.append(d)
print(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65]


## Frequent Letters
### Description
Given a string, you have to find the first n most frequent characters in it.
<br>
You have to print these n letters in alphabetically sorted order.
<br>
The input will contain two lines, the first line will contain a string and the second line will contain the letter n.
<br>
The output should be a list of n most frequent letters in alphabetically sorted order.
<br>
Note: If there are two letters with the same frequency, then the alphabetically preceding alphabet should be <br>picked first. (For example, in "aabbccc", if n=2, then output list would have c and a.)
<br>
Sample Input:
<br>
ddddaacccb
<br>
3
<br>
Sample Output:
<br>
['a', 'c', 'd']<br>

In [117]:
import collections
s = "aabbddccc"
n=2

[('c', 3), ('a', 2), ('b', 2), ('d', 2)]


In [118]:
d = collections.defaultdict(int)
for c in s:
    d[c] += 1
dic=sorted(d.items(), key=lambda x: (x[1]), reverse=True)
print(dic)

[('c', 3), ('a', 2), ('b', 2), ('d', 2)]


In [128]:
dic_temp=dic[0:n]
#print(dic_temp)
result=[]
for item in dic[0:n]:
    result.append(item[0])
print(sorted(result))

['a', 'c']


In [120]:
mykeys=d.keys()
arr=[]
for x in mykeys:
    value=str(d[x])
    value+=x
    arr.append(value)

In [121]:
print(arr)

['2a', '2b', '2d', '3c']


In [72]:
arr.sort()

In [73]:
print(arr)

['1d', '1e', '1h', '1r', '1w', '2o', '3l']


In [74]:
sorted(arr, key=lambda x: x[1], reverse=True)

['1w', '1r', '2o', '3l', '1h', '1e', '1d']